# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 0, size: 0.163, name: tag0},
    {id: 1, size: 0.163, name: tag1},
    {id: 2, size: 0.163, name: tag2},
    {id: 3, size: 0.173, name: tag3},
    {id: 4, size: 0.163, name: tag4},
    {id: 5, size: 0.163, name: tag5},
    {id: 6, size: 0.163, name: tag6},
    {id: 7, size: 0.163, name: tag7},
    {id: 8, size: 0.163, name: tag8},
    {id: 9, size: 0.163, name: tag9},
    {id: 10, size: 0.163, name: tag10},
    {id: 11, size: 0.163, name: tag11},
    {id: 12, size: 0.163, name: tag12},
    {id: 13, size: 0.163, name: tag13},
    {id: 14, size: 0.163, name: tag14},
    {id: 15, size: 0.163, name: tag15},
    {id: 16, size: 0.163, name: tag16},
    {id: 17, size: 0.173, name: tag17},
    {id: 18, size: 0.163, name: tag18},
    {id: 19, size: 0.173, name: tag19},
    {id: 20, size: 0.163, name: tag20},
    {id: 21, size: 0.163, name: tag21},
    {id: 22, size: 0.163, name: tag22},
    {id: 23, size: 0.163, name: tag23},
    {id: 24, size: 0.163, name: tag24},
    {id: 25, size: 0.163, name: tag25},
    {id: 26, size: 0.163, name: tag26},
    {id: 27, size: 0.163, name: tag27},
    {id: 28, size: 0.163, name: tag28},
    {id: 29, size: 0.163, name: tag29},
    {id: 30, size: 0.163, name: tag30},
    {id: 31, size: 0.163, name: tag31},
    {id: 32, size: 0.163, name: tag32},
    {id: 33, size: 0.163, name: tag33},
    {id: 34, size: 0.163, name: tag34},
    {id: 35, size: 0.163, name: tag35},
    {id: 36, size: 0.163, name: tag36},
    {id: 37, size: 0.163, name: tag37},
    {id: 38, size: 0.163, name: tag38},
    {id: 39, size: 0.163, name: tag39},
    {id: 40, size: 0.163, name: tag40},
    {id: 41, size: 0.163, name: tag41},
    {id: 42, size: 0.163, name: tag42},
    {id: 43, size: 0.163, name: tag43},
    {id: 44, size: 0.163, name: tag44},
    {id: 45, size: 0.163, name: tag45},
    {id: 46, size: 0.163, name: tag46},
    {id: 47, size: 0.163, name: tag47},
    {id: 48, size: 0.163, name: tag48},
    {id: 49, size: 0.163, name: tag49},
    {id: 60, size: 0.163, name: tag60},
    {id: 61, size: 0.163, name: tag61},
    {id: 62, size: 0.163, name: tag62}
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
  ]
